---
  - name: Download the argument's template files -> /opt/casfw
    template: src=data-match-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force
    tags:
      - copybashscript

  - name: search if there is the data-match instance process
    shell: cd {{ casfw_home }}/current/{{ data_match_instance }}
    register: foo_result
    ignore_errors: True
          
  - name: stop current tomcat process
    action: command bash {{ casfw_home }}/data-match-functions.sh stopTomcatPS
    when: foo_result.rc == 0
    tags:
      - stopTomcatPS
          
  - name: clean up data-match instances
    action: command bash {{ casfw_home }}/data-match-functions.sh cleanupInstance
    tags:
      - cleanupInstance
         
  - name: clean up the current
    action: command bash {{ casfw_home }}/data-match-functions.sh cleanupCurrent
    tags:
      - cleanupCurrent
          
  - name: Download the argument's template files -> {{ casfw_home }}
    template: src={{ item }} dest={{ casfw_home }} mode=0664 owner=casfw force
    with_items:
      - "data-match-cdi-args.txt"
      - "soap_envelope.xml"
    tags:
      - downloadarguments

  - name: Check tomcat process stopped
    action: command bash {{ casfw_home }}/data-match-functions.sh checkTomcatProcessStopped
    register: checkTomcatProcessStoppedResponse
    tags:
      - checkTomcatProcessStopped

  - name: install new cdi
    action: command bash {{ casfw_home }}/data-match-functions.sh installcdi
    when: checkTomcatProcessStoppedResponse.stdout == 'Tomcat Process Stopped'
    tags:
       - installcdi

  - name: Pause to make sure Apache instance process has started
    pause: minutes=1
    delegate_to: localhost
   
  - name: check instance
    action: command bash {{ casfw_home }}/data-match-functions.sh checkInstance
    tags:
      - checkInstance

  - name: check if the tomcat start with database loading
    action: command bash {{ casfw_home }}/data-match-functions.sh checkTomcatInstanceStartFinished
    register: check_result
    tags:
      - checkTomcatInstanceStartFinished

  - name: validate Restful Endpoint
    action: command bash {{ casfw_home }}/data-match-functions.sh restfulEndpointTest
    when: check_result.stdout == '</GetConfig>\nStart Finished' 
    # when: release_environment == 'dev'
    tags:
      - restfulEndpointTest
      
  - name: validate Soap Endpoint
    action: command bash {{ casfw_home }}/data-match-functions.sh soapEndpointTest
    tags:
      - soapEndpointTest

  - name: Sample validate Restful Endpoint Test
    action: command bash {{ casfw_home }}/data-match-functions.sh restValidationTest
    tags:
      - restValidationTest

  - name: Sample Validate Soap Endpoint Test
    action: command bash {{ casfw_home }}/data-match-functions.sh soapValidationTest
    tags:
      - soapValidationTest

  - name: Check databases loaded
    action: command bash {{ casfw_home }}/data-match-functions.sh checkDatabasesLoaded
    tags: 
      - checkDatabasesLoaded
   
  - name: Final cleanup
    action: command bash {{ casfw_home }}/data-match-functions.sh finalCleanup
    tags:
      - finalcleanup
 
            
