---
  - name: Download the argument's template files -> /opt/casfw
    template: src=ansible-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force
    tags:
      - copybashscript

  - name: search if there is the data-match instance process
    shell: cd {{ casfw_home }}/current/{{ data_match_instance }}
    register: foo_result
    ignore_errors: True
          
  - name: stop current tomcat process
    action: command bash {{ casfw_home }}/ansible-functions.sh stopTomcatPS
    when: foo_result.rc == 0
    tags:
      - stopTomcatPS
          
  - name: clean up data-match instances
    action: command bash {{ casfw_home }}/ansible-functions.sh cleanupInstance
    tags:
      - cleanupInstance
         
  - name: clean up the current
    action: command bash {{ casfw_home }}/ansible-functions.sh cleanupCurrent
    tags:
      - cleanupCurrent
          
  - name: Download the argument's template files -> {{ casfw_home }}
    template: src={{ item }} dest={{ casfw_home }} mode=0664 owner=casfw force
    with_items:
      - "{{ release_environment }}-data-match-cdi-args.txt"
      - "soap_envelope.xml"
    tags:
      - downloadarguments

  - name: install new cdi
    action: command bash {{ casfw_home }}/ansible-functions.sh installcdi
    tags:
       - installcdi
   
  - name: check instance
    action: command bash {{ casfw_home }}/ansible-functions.sh checkInstance
    tags:
      - checkInstance

  - name: Pause to make sure data-match instance process has started
    pause: minutes=6
    delegate_to: localhost

  - name: Check databases loaded
    action: command bash {{ casfw_home }}/ansible-functions.sh checkDatabasesLoaded
    tags: 
      - checkDatabasesLoaded

  - name: validate Restful Endpoint
    action: command bash {{ casfw_home }}/ansible-functions.sh restfulEndpointTest 
    # when: release_environment == 'dev'
    tags:
      - restfulEndpointTest
      
  - name: validate Soap Endpoint
    action: command bash {{ casfw_home }}/ansible-functions.sh soapEndpointTest
    tags:
      - soapEndpointTest 
   
  - name: Final cleanup
    action: command bash {{ casfw_home }}/ansible-functions.sh finalCleanup
    tags:
      - finalcleanup
 
            
