---
  - name: search if there is the data-match instance cdi
    shell: find {{ casfw_home }}/ -name data-match-installer-{{ data_match_release_version }}.cdi
    register: foo_result
    ignore_errors: True
    
  - name: clean up cdi packages
    shell: rm -rf {{ casfw_home }}/data-match-installer-{{ data_match_release_version }}.cdi
    when: foo_result.rc == 0
    tags:
      - cleanupcdi

  - name: download data-match installation CDI 
    action: command wget http://repo1.corp.hp.com/nexus/content/repositories/releases/com/hp/it/120482/data-match-installer/{{ data_match_release_version }}/data-match-installer-{{ data_match_release_version }}.cdi -P {{ casfw_home }}
    when: not datamatchsnapshot
    tags:
      - downloaddatamatchcdi

  - name: download data-match installation CDI (snapshot) 
    action: command wget -Nnv http://repo1.corp.hp.com/nexus/service/local/artifact/maven/redirect?r=snapshots&g=com.hp.it.120482&a=data-match-installer&v={{ data_match_release_version }}&e=cdi -O {{ casfw_home }}/data-match-installer-{{ data_match_release_version }}.cdi
    when: datamatchsnapshot
    tags:
      - downloaddatamatchsnapshotcdi   
  
  - include: deploy.yml data_match_instance=data-match1 release_env=ITG1 port=8380
  - include: deploy.yml data_match_instance=data-match2 release_env=ITG2 port=8390
  - include: deploy.yml data_match_instance=data-match3 release_env=ITG3 port=8400
