---
# This playbook is for Address Doctor tomcat instance restart
  - name: Download the argument's template files -> /opt/casfw
    template: src=db-restart-tomcat-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force

  - name: Stop tomcat instance
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh stopTomcatInstance

  - name: Wait for data-match port to stopped
    wait_for: host={{ inventory_hostname }} port={{ port }} delay=15 state=stopped
    su: no
    delegate_to: localhost

  - name: Start tomcat instance
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh startTomcatInstance

  - name: Wait for data-match port to started
    wait_for: host={{ inventory_hostname }} port={{ port }} delay=15 state=started
    su: no
    delegate_to: localhost

  - name: Wait for data-match databases load are finished and data-match instance start finished
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh waitDatabasesLoadFinished
    register: waitDatabasesLoadFinishedResponse

  - name: Check databases loaded
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh checkDatabasesLoaded
    when: waitDatabasesLoadFinishedResponse.stdout == 'Databases Load Finished'

  - name: Validate data-match Restful Endpoint
    uri: url=http://{{ inventory_hostname }}:{{ port }}/match/{{ item }}/documentation
    retries: 5
    delegate_to: localhost
    su: no
    with_items:
      - validatedAddress
      - certifiedAddress
      - looselyValidatedAddress
      - addressSuggestions
      - fastCompletionAddress

  - name: Validate data-match Soap Endpoint
    uri: url=http://{{ inventory_hostname }}:{{ port }}/legacy-match/address/v1?wsdl
    retries: 5
    delegate_to: localhost
    su: no

  - name: Sample validate Restful Endpoint Test
    uri: url=http://{{ inventory_hostname }}:{{ port }}/match/{{ item }}?country1=US&deliveryAddressLine1=745+Riverhaven+Drive&characterScriptDetectionIndicator=false&postalCode1=30024 HEADER_X-HP-Application-Process-UID="w-mdcp:prd-http"
    retries: 5
    delegate_to: localhost
    su: no
    with_items:
      - validatedAddress
      - certifiedAddress
      - looselyValidatedAddress
      - addressSuggestions
      - fastCompletionAddress

  - name: Download soap address xml input test file -> /opt/casfw
    template: src=soap_envelope.xml dest={{ casfw_home }} mode=0664 owner={{ useraccount }} group={{ usergroup }} force

  - name: Sample Validate Soap Endpoint Test
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh soapValidationTest
    register: soap_address_validate_result
  - debug: msg="{{ soap_address_validate_result.stdout }}"

  - name: Final Cleanup
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh finalCleanup