---
########## Copy Template files #################

  - name: Download the argument's template files -> {{ casfw_home }}
    template: src=db-download-functions.sh dest={{ casfw_home }} mode=0755 owner=casfw force
    tags:
      - copybashscript

  - name: Download the argument's template files -> {{ casfw_home }}
    template: src=db-download-args.txt dest={{ casfw_home }} mode=0664 owner=casfw force
    tags:
      - downloadarguments

########## Initial Environment #################
  - name: Initial Environment
    action: command bash {{ casfw_home }}/db-download-functions.sh initial
    tags: 
      - initial

########## Download oracle-java7  #################
  - name: Download oracle-java7
    action: command wget -Nnv http://repo1.corp.hp.com/nexus/content/repositories/thirdparty/com/oracle/java/oracle-java/{{ oracle_java_version }}/oracle-java-{{ oracle_java_version }}-linux-x64.tar.gz -P {{ software_dir }}
    tags:
      - downloadOracleJava7

###### Install oracle-java7 #################
  - name: Install oracle-java7
    action: command bash {{ casfw_home }}/db-download-functions.sh installJava7
    tags: 
      - installJava7

########## Download DB Downloadtool and download.xml file  #################

  - name: Download DB Downloadtool
    action: command wget -Nnv http://repo1.corp.hp.com/nexus/content/repositories/thirdparty/com/addressdoctor/Downloadtool/{{ downloadtool_version }}/Downloadtool-{{ downloadtool_version }}.zip -P {{ adm_client_folder }}
    tags:
      - downloadDBDownloadtool

  - name: Download download.xml file
    action: command wget -Nnv http://repo1.corp.hp.com/nexus/content/repositories/thirdparty/com/addressdoctor/download/{{ download_xml_version }}/download-{{ download_xml_version }}.zip -P {{ adm_client_folder }}
    tags:
      - downloadXMLfile 

########## Prepare Downloadtool #################
  - name: Prepare Downloadtool
    action: command bash {{ casfw_home }}/db-download-functions.sh prepareDownloadtool
    tags: 
      - prepareDownloadtool

########## Start Download DB #################
  - name: Start Download DB
    action: command bash {{ casfw_home }}/db-download-functions.sh downloadDB
    tags:
      - downloadDB

########## Final Cleanup #################
  - name: Final Cleanup
    action: command bash {{ casfw_home }}/db-download-functions.sh finalCleanup
    tags:
      - finalCleanup