---
# This playbook is for Address Doctor tomcat instance restart
  - name: Download the argument's template files -> {{ casfw_home }}
    template: src=db-restart-tomcat-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force

  - name: Download the argument's template files -> {{ casfw_home }}
    template: src=soap_envelope.xml dest={{ casfw_home }} mode=0664 owner={{ useraccount }} group={{ usergroup }}  force

  - name: Stop tomcat instance
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh stopTomcatInstance

  - name: Check tomcat process stopped
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh checkTomcatProcessStopped
    register: checkTomcatProcessStoppedResponse

  - name: Start tomcat instance
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh startTomcatInstance
    when: checkTomcatProcessStoppedResponse.stdout == 'Tomcat Process Stopped'

  - name: Check tomcat process started
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh checkTomcatProcessStarted
    register: checkTomcatProcessStartedResponse

  - name: Check tomcat instance start finished
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh checkTomcatInstanceStartFinished
    register: checkTomcatInstanceStartFinished
    when: checkTomcatProcessStartedResponse.stdout == 'Tomcat Process Started'

  - name: Check databases loaded
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh checkDatabasesLoaded
    when: checkTomcatInstanceStartFinished.stdout == 'Tomcat Instance Start Finished'

  - name: Validate Restful Endpoint
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh restfulEndpointTest 

  - name: Validate Soap Endpoint
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh soapEndpointTest

  - name: Sample validate Restful Endpoint Test
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh restValidationTest

  - name: Sample Validate Soap Endpoint Test
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh soapValidationTest

  - name: Final Cleanup
    action: command bash {{ casfw_home }}/db-restart-tomcat-functions.sh finalCleanup