---
# This playbook is for Address Doctor databases deployment.
########## Copy Template files #################
  - name: Download the argument's template files -> {{ casfw_home }}
    template: src=db-deploy-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force
    tags:
      - copybashscript

########## Check Disk Space #################
  - name: Check Disk Space
    action: command bash {{ casfw_home }}/db-deploy-functions.sh checkDiskSpace
    tags:
      - checkDiskSpace
    ignore_errors: no

########## Initial DB Latest Version Folder #################
  - name: Initial DB Target Folder
    action: command bash {{ casfw_home }}/db-deploy-functions.sh initialDBLatestVersionFolder
    tags:
      - initialDBLatestVersionFolder

########## Copy databases to target server #################
  - name: Copy database to target server
    copy: src={{ item }} dest={{ db_target_folder }}/{{ db_latest_version }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force
    with_fileglob:
      - "{{ db_source_folder }}/*.MD"
    tags:
      - copyDBFilesToTargetServer

########## Update DB Symlink #################
  - name: Update DB SymLink
    action: command bash {{ casfw_home }}/db-deploy-functions.sh updateDBSymLink
    tags:
      - updateDBSymLink

########## Restart Tomcat instances #################
  - include: db-restart-tomcat.yml data_match_instance={{ data_match_instance1 }} port={{ tomcat_ad_port1 }}
  - include: db-restart-tomcat.yml data_match_instance={{ data_match_instance2 }} port={{ tomcat_ad_port2 }}
  - include: db-restart-tomcat.yml data_match_instance={{ data_match_instance3 }} port={{ tomcat_ad_port3 }}

########## Final Cleanup #################
  - name: Final Cleanup
    action: command bash {{ casfw_home }}/db-deploy-functions.sh finalCleanup
    tags:
      - finalCleanup