---
# This playbook is for Address Doctor databases deployment.
  - name: Download the argument's template files -> {{ casfw_home }}
    template: src=db-deploy-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force

  - name: Check Disk Space
    action: command bash {{ casfw_home }}/db-deploy-functions.sh checkDiskSpace

  - name: Initial DB Target Folder
    action: command bash {{ casfw_home }}/db-deploy-functions.sh initialDBLatestVersionFolder

  - name: Copy database to target server
    copy: src={{ item }} dest={{ db_target_folder }}/{{ db_latest_version }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force
    with_fileglob:
      - "{{ db_source_folder }}/*.MD"

  - name: Update DB SymLink
    action: command bash {{ casfw_home }}/db-deploy-functions.sh updateDBSymLink

  - include: db-restart-tomcat.yml data_match_instance={{ data_match_instance1 }} port={{ tomcat_ad_port1 }}
  - include: db-restart-tomcat.yml data_match_instance={{ data_match_instance2 }} port={{ tomcat_ad_port2 }}
  - include: db-restart-tomcat.yml data_match_instance={{ data_match_instance3 }} port={{ tomcat_ad_port3 }}

  - name: Final Cleanup
    action: command bash {{ casfw_home }}/db-deploy-functions.sh finalCleanup