---
- name: Copy init-casfw to /tmp dir
  copy: src=init-casfw dest=/tmp mode="a=rwx" force
  su: no

- name: Copy the auto-start-functions.sh to the users home directory
  template: src=auto-start-functions.sh dest=~/ mode="a=rwx" force
  su: no

- name: Server Initial setup validation
  shell: whoami ; pwd ; ./auto-start-functions.sh serverInitialValidation
  su: no
  register: serverinitialresponse

- name: Server Initial Setup by root
  shell: whoami ; pwd ; ./auto-start-functions.sh serverInitialSetup
  su: yes
  su_user: root
  when: "'Not installed' in serverinitialresponse.stdout"
  ignore_errors: yes

- name: Copy the casfw file to /opt/casfw/bin/
  copy: src=casfw dest={{ casfw_home }}/bin/ mode="u+rwx,g+rx,o+rx" owner={{ useraccount }} group={{ usergroup }} force

- name: Copy the data-match files to /opt/casfw/init.d/
  copy: src={{ item }} dest={{ casfw_home }}/init.d/ mode="u+rwx,g+rx,o+rx" owner={{ useraccount }} group={{ usergroup }} force
  with_items:
    - data-match-1
    - data-match-2
    - data-match-3

- name: Remove shell script functions from the destination server
  shell: ./auto-start-functions.sh finalCleanup
  su: no
