---
  - name: Copy the su file to users home directory
    copy: src=su.sh dest=~/ mode=0755 force
    su: no
    tags:
      - copysuscript

  - name: Copy the init-casfw file to /tmp/
    copy: src=init-casfw dest=/tmp/ mode="a=rwx" force
    su: no

  - name: Server Initial setup validation
    script: common-functions.sh serverInitialValidation
    su: no
    register: serverinitialresponse

  - name: Server Initial Setup by root
    script: common-functions.sh serverInitialSetup
    su: yes
    su_user: root
    when: "'Not installed' in serverinitialresponse.stdout"
    ignore_errors: yes

  - name: Copy the casfw file to /opt/casfw/bin/
    copy: src=casfw dest={{ casfw_home }}/bin/ mode="u+rwx,g+rx,o+rx" owner={{ useraccount }} group={{ usergroup }} force

  - name: Create /opt/casfw/init.d/ symlinks
    file:
      src: "{{ casfw_home }}/{{ item.instance }}/data-match-{{ data_match_release_version }}/bin/data-match"
      dest: "{{ casfw_home }}/init.d/{{ item.symlink }}"
      state: link
      force: yes
    with_items:
      - { instance: "data-match1", symlink: "data-match-1" }
      - { instance: "data-match2", symlink: "data-match-2" }
      - { instance: "data-match3", symlink: "data-match-3" }

  - name: Remove shell script functions from the destination server
    script: common-functions.sh finalCleanup
    su: no
