---
  - name: download the function template file -> /opt/casfw
    template: src=data-match-functions.sh dest={{ casfw_home }} mode=0755 owner={{ useraccount }} group={{ usergroup }} force

  - name: check status of data-match instance process
    action: command bash {{ casfw_home }}/data-match-functions.sh instanceRunningStatus
    register: instance_running_status

  - name: stop data-match instance process when running
    action: command bash {{ casfw_home }}/data-match-functions.sh stopInstanceProcess
    when: "'tomcat-ad running' in instance_running_status.stdout"
    ignore_errors: yes

  - name: initial cleanup - remove instance directory and instance current symbol link
    action: command bash {{ casfw_home }}/data-match-functions.sh initialCleanup

  - name: download the argument's template files -> {{ casfw_home }}
    template: src=data-match-cdi-args.txt dest={{ casfw_home }} mode=0664 owner={{ useraccount }} group={{ usergroup }} force

  - name: wait for data-match port to stopped
    wait_for: host={{ inventory_hostname }} port={{ port }} delay=15 state=stopped
    su: no
    delegate_to: localhost

  - name: deploy data-match CDI
    action: command bash {{ casfw_home }}/data-match-functions.sh installcdi

  - name: wait for data-match port to started
    wait_for: host={{ inventory_hostname }} port={{ port }} delay=15 state=started
    su: no
    delegate_to: localhost

  - name: wait for data-match database load is finished
    wait_for: path={{ casfw_home }}/current/{{ data_match_instance }}/var/log/data-match-web/ad-engine.log search_regex=</GetConfig> timeout=600

  - name: check databases loaded
    action: command bash {{ casfw_home }}/data-match-functions.sh checkDatabasesLoaded

  - name: validate Restful Endpoint
    action: command bash {{ casfw_home }}/data-match-functions.sh restfulEndpointTest 

  - name: validate Soap Endpoint
    action: command bash {{ casfw_home }}/data-match-functions.sh soapEndpointTest

  - name: sample validate Restful Endpoint Test
    action: command bash {{ casfw_home }}/data-match-functions.sh restValidationTest

  - name: download soap test file -> {{ casfw_home }}
    template: src=soap_envelope.xml dest={{ casfw_home }} mode=0664 owner={{ useraccount }} group={{ usergroup }} force

  - name: sample Validate Soap Endpoint Test
    action: command bash {{ casfw_home }}/data-match-functions.sh soapValidationTest

  - name: final cleanup
    action: command bash {{ casfw_home }}/data-match-functions.sh finalCleanup