---
########## Template files copy and init cleanup #################

  - name: Download the argument's template files -> /opt/casfw
    template: src=proxy-functions.sh dest={{ casfw_home }} mode=0755 owner=casfw group=casfwgrp force
    tags:
      - copybashscript
  - name: Initial Cleanup - remove old symbol link
    action: command bash {{ casfw_home }}/proxy-functions.sh initialCleanup
    tags:
      - initialcleanup
  - name: Remove the existing version of the proxy-bundle
    action: command bash {{ casfw_home }}/proxy-functions.sh cleanupProxyBundle
    tags:
      - cleanupproxybundle

########## Download Proxy Bundle #################

  - name: Download proxy-bundle installation CDI
    action: command wget -Nnv http://repo1.corp.hp.com/nexus/content/groups/public/com/hp/it/120482/proxy-bundle-installer/{{ proxy_bundle_version }}/proxy-bundle-installer-{{ proxy_bundle_version }}.cdi -O {{ casfw_home }}/proxy-bundle-installer-{{ proxy_bundle_version }}.cdi
    when: not proxybundlesnapshot
    tags:
      - downloadproxybundlecdi
  - name: Download proxy-bundle installation CDI (snapshot)
    action: command wget -Nnv http://repo1.corp.hp.com/nexus/service/local/artifact/maven/redirect?r=snapshots&g=com.hp.it.120482&a=proxy-bundle-installer&v={{ proxy_bundle_version }}&e=cdi -O {{ casfw_home }}/proxy-bundle-installer-{{ proxy_bundle_version }}.cdi
    when: proxybundlesnapshot
    tags:
      - downloadproxybundlesnapshotcdi

########## Deploy Proxy Bundle #################

  - name: Deploy proxy-bundle CDI
    action: command bash {{ casfw_home }}/proxy-functions.sh installProxyBundleCdi
    tags: 
      - deployproxybundlecdi
  - name: Create proxy-bundle Symbol Link
    action: command bash {{ casfw_home }}/proxy-functions.sh createProxyBundleLink
    tags: 
      - createproxybundlelink

########## Restart apache instance #################

  - name: Restart Apache Instance
    action: command bash {{ casfw_home }}/proxy-functions.sh restartApacheInstance
    when: not iscloudserver
    tags:
      - restartapacheinstance
  - name: Restart Cloud Apache Instance
    action: command bash {{ casfw_home }}/proxy-functions.sh restartCloudApacheInstance
    when: iscloudserver
    tags:
      - restartcloudapacheinstance

########## Final Cleanup and validation #################

  - name: Final cleanup
    action: command bash {{ casfw_home }}/proxy-functions.sh finalCleanup
    tags:
      - finalcleanup
  - name: Pause to make sure Apache instance process has started
    pause: minutes=1
    delegate_to: localhost
  - name: validate apache instance health page
    uri: url={{ item.url }} status_code={{ item.statuscode }}
    retries: 5
    delegate_to: localhost
    su: no
    with_items:
      #TODO- http://{{ inventory_hostname }}:1180/DO_NOT_REMOVE/welcome.jsp
      - { url: 'http://{{ inventory_hostname }}:1180/DO_NOT_REMOVE/welcome.jsp', statuscode: 200}
      - { url: 'http://{{ inventory_hostname }}:1180/DO_NOT_REMOVE/welcome.txt', statuscode: 200}
      - { url: 'http://{{ inventory_hostname }}:1180/DO_NOT_REMOVE/health_check.htm', statuscode: 200}
      - { url: 'http://{{ inventory_hostname }}:1180/DO_NOT_REMOVE/static_test.htm', statuscode: 200}
      - { url: 'http://{{ inventory_hostname }}:1180/match/about/health', statuscode: 204}
    tags:
      - validateinstallation