---
#This playbook for Address-Service Monitoring
- hosts: as-monitoring
  gather_facts: no
  tasks:
  - name: Address-Service Monitoring
    local_action: shell url="http://{{ inventory_hostname }}/{{ item }}"; status=$(curl -o "/dev/null" -s -w "%{http_code}" "${url}"); if [[ ${status} -ne 200 ]]; then echo "${JOB_NAME}-${BUILD_NUMBER} ${url} ${status}" >> as-monitor-result.txt; echo ${status}; fi
    retries: 5
    with_items:
      - "{{ health_check_url }}"
      - legacy-match/address/v1?wsdl
      - match/validatedAddress/documentation