---
#This playbook deployment for data-match auto start when server reboot
- hosts: data-match
  su: yes
  su_user: casfw
  gather_facts: no
  serial: 1
  roles:
  - common
  - data-match-auto-start
  - common-cleanup
