---
#This playbook deploys an CAS Address Doctor Application
- hosts: data-match
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    data_match_release_version: 2016.04.r3
    datamatchsnapshot: false
    nexus_host: repo1.core.hpecorp.net
  vars_files:
  - roles/data-match/vars/{{ release_environment }}-vars.yml
  roles:
  - common
  - data-match
  - data-match-proxy
  - common-cleanup
