#This playbook deploys an CAS Address Doctor Proxy Bundle
- hosts: data-match
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    data_match_release_version: @@data_match_release_version@@
    data_match_instance: @@data_match_instance@@
    release_env: @@release_env@@
    port: @@port@@
    release_environment: @@release_environment@@
    casfw_home: /opt/casfw
    datamatchsnapshot: @@data_match_snapshot@@
    useraccount: casfw
    usergroup: casfwgrp
  roles:
  - common
  - data_match
