- hosts: data-match
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    data_match_release_version: 2015.02.01
    data_match_instance: data-match2
    casfw_home: /opt/casfw
    useraccount: casfw
    usergroup: casfwgrp
  roles:
  - database_check