---
#This playbook deploys an CAS Address Doctor Application
- hosts: data-match
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    data_match_release_version: 1.0.34
    datamatchsnapshot: false
  vars_files:
  - roles/data-match/vars/{{ release_environment }}-vars.yml
  roles:
  - data-match
