---
#This playbook deploys an CAS Address Doctor Application
- hosts: data-match
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    data_match_release_version: @@data_match_release_version@@
    datamatchsnapshot: false
  vars_files:
  - /vars/{{ release_environment }}-vars.yml
  roles:
  - data-match
