
---
# This playbook for Address Doctor databases deployment.
- hosts: db-deploy
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    db_source_folder: /tmp/address-doctor/databases/stage
    db_target_folder: /opt/casfw/address-doctor/databases
    db_latest_version: @@db_latest_version@@
    data_match_instance1: data-match1
    data_match_instance2: data-match2
    data_match_instance3: data-match3
    tomcat_ad_port1: 8380
    tomcat_ad_port2: 8390
    tomcat_ad_port3: 8400
  roles:
  - db-deploy