
---
# This playbook for Address Doctor databases deployment.
- hosts: DB-DEPLOY
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    casfw_home: /opt/casfw
    useraccount: casfw
    usergroup: casfwgrp
    db_source_folder: @@db_source_folder@@
    db_target_folder: @@db_target_folder@@
    data_match_instance1: data-match1
    data_match_instance2: data-match2
    data_match_instance3: data-match3
    tomcat_ad_port1: 8380
    tomcat_ad_port2: 8390
    tomcat_ad_port3: 8400
  roles:
  - common
  - dbdeploy