
---
# This playbook for Address Doctor databases download
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  serial: 1
  vars:
    downloadtool_version: @@downloadtool_version@@
    download_xml_version: @@download_xml_version@@
    adm_client_folder: @@adm_client_folder@@
    jdk_verion: 1.7.0_65
    https_proxy_host: @@https_proxy_host@@
    https_proxy_port: @@https_proxy_port@@
    casfw_home: /opt/casfw
    useraccount: casfw
    usergroup: casfw
    db_download_server: @@db_download_server@@
    db_folder: @@db_folder@@
  vars_files:
    - roles/dbdownload/vars/vars.yml
  roles:
  - common
  - dbdownload