
---
# This playbook for Address Doctor databases download
- hosts: db-download
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    downloadtool_version: @@downloadtool_version@@
    download_xml_version: @@download_xml_version@@
    adm_client_folder: /opt/casfw/address-doctor/databases/ADM-Client
    db_folder: /opt/casfw/address-doctor/databases/stage
    jdk_verion: 1.7.0_65
    https_proxy_host: web-proxy.austin.hp.com
    https_proxy_port: 8088
    casfw_home: /opt/casfw
    useraccount: casfw
    usergroup: casfwgrp
  roles:
  - common
  - db-download