
---
# This playbook for Address Doctor databases deployment.
- hosts: DB-{{ deploy_env }}
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    casfw_home: /opt/casfw
    useraccount: casfw
    usergroup: casfw
    deploy_env: @@deploy_env@@
    db_source_folder: @@db_source_folder@@
    db_target_folder: @@db_target_folder@@
  roles:
  - common
  - dbdeploy