
---
# This playbook for Address Doctor databases download
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  serial: 1
  vars:
    downloadtool_version: @@downloadtool_version@@
    download_xml_version: @@download_xml_version@@
    adm_client_folder: /tmp/address-doctor/databases/ADM-Client
    jdk_verion: 1.7.0_65
    https_proxy_host: web-proxy.austin.hp.com
    https_proxy_port: 8088
    casfw_home: /tmp
    useraccount: jenkins
    usergroup: jenkins
  roles:
  - db-download