
---
# This playbook for Address Doctor databases download
- hosts: dbserver
  gather_facts: no
  serial: 1
  su: yes
  su_user: casfw
  vars:
    downloadtool_version: 1.0
    download_xml_version: demo
    adm_client_folder: /opt/casfw/address-doctor/databases/ADM-Client
    jdk_verion: 1.7.0_65
    https_proxy_host: web-proxy.austin.hp.com
    https_proxy_port: 8088
    user_name: santhosh.chandan@hp.com
    password: Anagha@123
    casfw_home: /opt/casfw
    useraccount: casfw
    usergroup: casfw
  roles:
  - common
  - dbdownload