---
  - name: validate LB apache health page
    uri: url=https://{{ item }}/{{ health_check_url }} status_code=200
    retries: 5
    delegate_to: localhost
    with_items: "{{ groups['lb-alias'] }}"

  - name: validate LB data-match health page
    uri: url=https://{{ item }}/match/about/health status_code=204
    retries: 5
    delegate_to: localhost
    with_items: "{{ groups['lb-alias'] }}"

  - name: validate LB data-match restful endpoint
    uri: url=https://{{ item[0]  }}/match/{{ item[1] }}/documentation status_code=200
    retries: 5
    delegate_to: localhost
    with_nested:
      - "{{ groups['lb-alias'] }}"
      - [ validatedAddress, certifiedAddress, looselyValidatedAddress, addressSuggestions, fastCompletionAddress ]

  - name: validate LB data-match soap endpoint
    uri: url=https://{{ item }}/legacy-match/address/v1?wsdl status_code=200
    retries: 5
    delegate_to: localhost
    with_items: "{{ groups['lb-alias'] }}"

  - name: validate LB data-match restful addresses
    uri: url=https://{{ item[0] }}/match/{{ item[1] }}?country1=US&deliveryAddressLine1=745+Riverhaven+Drive&characterScriptDetectionIndicator=false&postalCode1=30024 HEADER_X-HP-Application-Process-UID="w-mdcp:prd-http"
    retries: 5
    delegate_to: localhost
    with_nested:
      - "{{ groups['lb-alias'] }}"
      - [ validatedAddress, certifiedAddress, looselyValidatedAddress, addressSuggestions, fastCompletionAddress ]

  - name: validate LB data-match soap addresses
    script: acceptance-test-functions.sh soapValidationTest {{ item }}
    with_items: "{{ groups['lb-alias'] }}"

########## SSL Check ##########
  - name: SSL Check with jrunscript command
    script: acceptance-test-functions.sh jrunscriptTest {{ item }} {{ health_check_url }}
    with_items: "{{ groups['lb-alias'] }}"
    when: "'{{ release_environment }}' != 'dev'"

  - name: SSL Check with curl command
    script: acceptance-test-functions.sh curlTest {{ item }}
    with_items: "{{ groups['lb-alias'] }}"
    when: "'{{ release_environment }}' != 'dev'"

########## RDI Result Verification ##########
  - name: Check RDI feature which is in Certifed Mode Verification for US address
    uri:
      url=https://{{ item }}/match/certifiedAddress?country1=US&deliveryAddressLine1=11925%20Jones%20RD&locality1=Houston&postalCode1=77070&province1=TX
      status_code=200
      HEADER_X-HP-Application-Process-UID=hpit:CD-TEST
    retries: 5
    delegate_to: localhost
    with_items: "{{ groups['lb-alias'] }}"
    register: returnResult

  - debug: msg="It is residential address and the RDI should be returned with Y."
    delegate_to: localhost
    with_items: returnResult.results
    when: ("{{ item.json.content.resultData[0].cass[18].type }}" == "RDI" and "{{ item.json.content.resultData[0].cass[18].value }}" == "Y")
###### Check Supplementary issue for country Germany (ISO2 DE)########
  - name: Check Supplementary issue for country Germany (ISO2 DE)
    uri: url=http://{{ item }}/match/validatedAddress?country1=DE&locality1=Dortmund&province1=Nordrhein-Westfalen&postalCode1=44287&deliveryAddressLine1=Riesestr. 19&characterScriptDetectionIndicator=true HEADER_X-HP-Application-Process-UID="w-mdcp:prd-http"
    retries: 5
    delegate_to: localhost
    with_items: "{{ groups['lb-alias'] }}"

###### Check Supplementary issue for country Switzerland (ISO2 CH) ################## 
  - name: Check Supplementary issue for country Switzerland (ISO2 CH)
    uri: url=http://{{ item }}/legacy-match/address/v1?wsdl status_code=200
    retries: 5
    delegate_to: localhost
    with_items: "{{ groups['lb-alias'] }}"
