#!/bin/bash

#
# Controls all CAS services located on this server. Each individual service
# is controlled here as a group. All services are started, stopped and
# restarted via the specific control scripts for each service.

CASFW_HOME="$(cd "$(dirname "$0")/.." && pwd -P)"
INIT=$CASFW_HOME/init.d
USER="casfw"
TOMCATPIDFILE="${CASFW_HOME}/data-match1/data-match*/var/tomcat-ad.pid"


#echo "$(id -un) 0=$0 @=$@"

# ----------------------------------------------------------------------

if [ $(id -un) != "${USER}" ]
then
        exec su -m "${USER}" -c "$0 $@"
fi

# ----------------------------------------------------------------------

start() {
	nohup $CASFW_HOME/data-match1/data-match*/bin/tomcat-ad.sh start > /dev/null 2>&1&
}

stop() {
	$CASFW_HOME/data-match1/data-match*/bin/tomcat-ad.sh stop -force
	sleep 10
	status
}

restart() {
    stop
    start
    status
}

status() {
	checkTomcatPid
}

checkTomcatPid() {
    if getTomcatPid $TOMCATPIDFILE; then
            echo "Data Match 1 Running"
            return 0;
    else
            echo "Data Match 1 Stopped"
            return 1;
    fi
}

getTomcatPid() {
    local pidfile="$1"
    if [ ! -f $pidfile ]; then
            return 1;
    fi
    pid="$(<$pidfile)"
    checkTomcatStatus $pid || return 1
    return 0;
}

checkTomcatStatus() {
    local pid="$1"
    if [ -z "$pid" -o "$pid" == " " ]; then
            return 1;
    fi
    if [ ! -e /proc/$pid ]; then
            return 1;
    fi
    return 0;
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart)
        restart
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

